import bcrypt from "bcrypt";
import {
	sequelize,
	Menu,
	Events,
	Gallery,
	Staff,
	Suppliers,
	Users,
} from "../models/index.js";

async function seed() {
	try {
await Menu.bulkCreate(
  rawItems().map((it) => ({
    ...it,
    slug_cat2: it.cat2 ? it.cat2.replace(/\s+/g, "_").toLowerCase() : null,
  }))
);

// Gardez votre tableau tel quel ici
function rawItems() {
  return [
    {
				cat1: "Boissons",
				cat2: "Le chaud",
				cat3: "Cafés",
				name: "Café bio et équitable 80% Arabica 20% Robusta",
				description: "(Pérou) Brûlerie de la Maine, Etriché",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "(bio)",
				petit: 1.6,
				grand: 3.0,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Le chaud",
				cat3: "Cafés",
				name: "Macchiato royal",
				description: "Café, Lait, Caramel ou Chocolat Maison,Chantilly",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: 4.5,
				grand: 7.0,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Le chaud",
				cat3: "Thés / infusions Dammann",
				name: "Jasmin",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Le chaud",
				cat3: "Thés / infusions Dammann",
				name: "Tisane Nuit à Versailles",
				description: "Bergamote, Kiwi, Pêche",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Softs",
				name: "Les diabolos",
				description:
					"Melon, Pastèque, Goyave, Litchi, Grenadine, Passion, Grenade, Fraise, Cerise, Cassis, Mûre, Framboise, Pêche, Menthe, Banulle, Violette, Kiwi, Rose, Orgeat, Gingembre, Pamplemousse, Citron, Citronnelle, Pulco",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 2.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Softs",
				name: "Boisson énergisante",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Bières et Vins Sans Alcool",
				name: "Tête Haute IPA Presque Sans Alcool 0,5%",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 5.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Bières et Vins Sans Alcool",
				name: "Vin Blanc Sans Alcool",
				description: "«Cypher» Domaine de Brau (Sauvignon)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Jus",
				name: "100% Pur Jus local",
				description: "Pomme (53), Raisin (49)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Jus",
				name: "Vergers de la Manse (37)",
				description:
					"Tomate, Pomme/Mangue, Pomme/Framboise, Poire, Anullas, Orange, Pamplemousse, Abricot, Fraise",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 4.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Eaux",
				name: "Eau Neuve",
				description: "Eau minérale gazeuse",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Eaux",
				name: "Plancoët Gazeuse",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 4.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Cocktails Sans Alcool",
				name: "Virgin Spritz, Virgin Hugo Spritz",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Softs et Sans Alcool",
				cat3: "Les Cocktails Sans Alcool",
				name: "Sawat",
				description: "Purée de Fraise, Jus de Cranberry, Menthe, Tonic",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Cocktails",
				cat3: "Les Cocktails Classiques",
				name: "Jäger Bomb, Ti Punch",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 5.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Cocktails",
				cat3: "Les Cocktails Classiques",
				name: "Caïpirinha, Caïpiroska",
				description: "Caïpirinha - fruits +0,50€",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Cocktails",
				cat3: "Les Cocktails du moment",
				name: "Red Mojito",
				description:
					"Rhum, Citron Vert, Menthe, Jus de Fleur d’Hibiscus, Angustura, Sucre",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Cocktails",
				cat3: "Les Cocktails du moment",
				name: "Spritz Violette",
				description: "Crème de Violette, Eau Gazeuse, Crémant",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Bières",
				cat3: "Pression française",
				name: "Slash Mango, Blonde, Fruitée",
				description: "Brasserie La Licorne, Saverne, 67",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: 4.2,
				pinte: 7.5,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Bières",
				cat3: "Pression française",
				name: "Panaché",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: 3.2,
				pinte: 5.5,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Bières",
				cat3: "Craft beer locales",
				name: "Gose",
				description: "Acidulée, Note Cassis & Citron vert",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Bières",
				cat3: "Craft beer locales",
				name: "Wheat Ale",
				description: "Bière de Blé, Légèrement Argumé",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Bières",
				cat3: "Bières bouteille",
				name: "Chouffe",
				description: "Blonde",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Bières",
				cat3: "Bières bouteille",
				name: "Kasteel Rouge",
				description: "Fruits Rouges",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Apéritifs",
				cat3: "",
				name: "Pastis",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Apéritifs",
				cat3: "",
				name: "Martini Blanc, Martini Rouge",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Rouges",
				cat3: "Val de Loire",
				name: "Anjour Rouge AOP",
				description: "Domaine des Hautes Ouches (Cab,Franc)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 2.5,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Rouges",
				cat3: "Val de Loire",
				name: "Anjou Rouge AOP",
				description: "Domaine du Gerfaut (Cab,Franc)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 3.5,
				bouteille: 18.0,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Rouges",
				cat3: "Les Autres Régions",
				name: "Bordeaux Rouge AOC « Réserve »",
				description: "Chateau la Grave de Bertin (Merlot, Cab,Franc, Cab,Sauv)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 3.6,
				bouteille: 19.0,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Rouges",
				cat3: "Les Autres Régions",
				name: "Gravé dans la Roche, IGP Coteaux du Pont du Gard",
				description: "Chateau Boucarut (Syrah, vin nature)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 3.9,
				bouteille: 21.5,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Blancs",
				cat3: "",
				name: "Côteaux de l’Aubance",
				description: "Domaine Papin (Chenin blanc)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 3.2,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Blancs",
				cat3: "",
				name: "Brut Traditionnel Val de Loire",
				description: "Bouvet Ladubay - 1851 (Chardonnay, Chenin)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 4.0,
				bouteille: 22.0,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Rosés",
				cat3: "",
				name: "Rosé de Loire AOP",
				description: "Domaine des Hautes Ouches (Grolleau, Gamay)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 2.5,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Les Vins Rosés",
				cat3: "",
				name: "IGP Méditerranée « Brise Marine »",
				description: "Cercle vignerons de provence (Grenache, Cinsault)",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: 3.2,
				bouteille: 16.0,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Pichet de vin",
				cat3: "",
				name: "Anjou Rouge AOP",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: null,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: 4.2,
				cl_50: 8.0,
				l_1: 15.0,
			},
			{
				cat1: "Boissons",
				cat2: "Pichet de vin",
				cat3: "",
				name: "Cidre Brut",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.8,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Rhums",
				cat3: "",
				name: "Rhum Arrangé Maison",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Rhums",
				cat3: "",
				name: "Botran",
				description: "doux, fruité",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Whiskies",
				cat3: "Single Malt",
				name: "Aberlour 10 ans",
				description: "fruité, épicé",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Whiskies",
				cat3: "Single Malt",
				name: "Laphroaig 10 ans",
				description: "tourbé",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Whiskies",
				cat3: "Blended",
				name: "Irish Powers",
				description: "fort caractère",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Whiskies",
				cat3: "Blended",
				name: "Monkey Shoulder",
				description: "rond, fruits frais",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Whiskies",
				cat3: "Bourbon",
				name: "Maker’s Mark",
				description: "doux",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 6.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Whiskies",
				cat3: "Bourbon",
				name: "Woodford Reserve",
				description: "boisé, rond",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 8.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Gins Tonics",
				cat3: "",
				name: "Gin Hendrick’s",
				description: "Schweppes Tonic",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.9,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Gins Tonics",
				cat3: "",
				name: "Gin Hendrick’s Orbium",
				description: "Fever Tree Tonic",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 9.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Digestifs",
				cat3: "",
				name: "Cointreau, Menthe, Pastille Giffard, Peppermint, Bailey's",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 5.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Digestifs",
				cat3: "",
				name: "Poire, Cognac aux Amandes Giffard, Calvados",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 5.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Shots",
				cat3: "",
				name: "Springbok, Tequila",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Shots",
				cat3: "",
				name: "Smooth and Easy",
				description: "Rhum, Mangue, Vanille",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Shots",
				cat3: "Rhum arrangé",
				name: "Rhum Arrangé",
				description: "Fraise, Basilic et Vanille",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Boissons",
				cat2: "Shots",
				cat3: "Rhum arrangé",
				name: "Rhum Arrangé",
				description: "Orange, Cannelle et Vanille",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 3.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Assiettes et Planches",
				cat3: "",
				name: "Tartinades Maison à Partager",
				description:
					"4 choix parmi: Houmous, Tzatziki, Rillettes de Thon, Écrasé d’Avocat, Rillettes Basques, Mozza",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 23.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Assiettes et Planches",
				cat3: "",
				name: "Camembert Rôti",
				description: "Camembert 150g, miel, thym",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Soupe/Gaspacho Maison",
				cat3: "",
				name: "Demandez au serveur pour la soupe du jour",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 5.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Salades",
				cat3: "",
				name: "Vosgienne",
				description:
					"Lardons, dés d’emmental, tomates séchées, salade, croûtons",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Salades",
				cat3: "",
				name: "César",
				description:
					"Poulet, grana padano, tomates séchées, champignons, sauce César, salade, croûtons",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Salades",
				cat3: "Végétarien",
				name: "Automnale",
				description: "Avocat, pommes, betteraves, noix, céleri, salade",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Salades",
				cat3: "Végétarien",
				name: "Estival",
				description: "Melon, feta, basilic, salade",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Salades de pâtes froides",
				cat3: "",
				name: "Provençale",
				description:
					"Courgettes, poivrons, aubergines, tomates, oignons, pâtes fusilli",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Salades de pâtes froides",
				cat3: "",
				name: "Saumon",
				description:
					"Saumon, billes de mozzarella di bufala, aneth, concombre, pâtes fusilli",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Bœuf",
				name: "Pitchoun",
				description: "Steak 90g, cheddar, salade, ketchup",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 8.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Bœuf",
				name: "Classique",
				description:
					"Steak, cheddar, cornichons, tomates, sauce cocktail, salade",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 9.9,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Végétarien",
				name: "Phénicien",
				description:
					"Falafel maison, cheddar, roquette, cornichons, tomates, salade, tzatziki maison",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Végétarien",
				name: "Veggie",
				description:
					"Galette de pommes de terre maison, aubergine, courgette, poivron, tomate, cheddar, cornichons, salade, sauce cocktail",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Poulet",
				name: "Chicken",
				description:
					"Poulet frit, gouda, cumin, cornichon, tomate, salade, sauce barbecue",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 12.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Poulet",
				name: "Héllène",
				description:
					"Filet de poulet citronné, roquette, cornichons, curcuma, tomates, salade, tzatziki maison",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 13.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Poisson",
				name: "Marin",
				description:
					"Filet de cabillaud pané, gouda, roquette, cornichons, tomates, salade, sauce tartare maison",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Pour les enfants",
				name: "Steak 90g",
				description: "Servi avec salade verte",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 8.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Burgers",
				cat3: "Pour les enfants",
				name: "Burger Pitchoun",
				description: "Steak 90g, cheddar, ketchup, salade",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Chaud",
				name: "Poulet",
				description:
					"Poulet, emmental, champignons, crème fraîche, tomates séchées",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Chaud",
				name: "Jambon",
				description:
					"Jambon Bodega 24 mois, mozzarella, champignons, sauce tomate maison",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Froid",
				name: "Norvégienne",
				description:
					"Saumon, noix, fromage frais, crème fraîche, curry, roquette, tomates cerises, ciboulette",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Froid",
				name: "Ibérique",
				description:
					"Crème de chorizo, olive verte et noire, roquette, ciboulette, tomates cerises, piment d’Espelette",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 11.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Végan Froid",
				name: "Avocado",
				description: "Olives, écrasé d’avocats, tomates cerises",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Végan Froid",
				name: "Levantine",
				description:
					"Houmous maison, aubergines, olives, roquette, tomates séchées",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Végétarien Chaud",
				name: "Chèvre",
				description: "Chèvre, noix, miel, menthe",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 9.9,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Tartines",
				cat3: "Végétarien Chaud",
				name: "Méditerranée",
				description: "Aubergines, mozzarella, parmesan, tomates séchées",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 10.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Plat du Jour",
				cat3: "",
				name: "Plat du jour",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 13.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Plat du Jour",
				cat3: "",
				name: "Plat + Dessert du Jour",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 17.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Plat du Jour",
				cat3: "",
				name: "Plat + Dessert + Verre de Vin + Café",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 19.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Plats",
				cat3: "",
				name: "Steak Haché 125g",
				description: "Sauce au choix",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 9.9,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Plats",
				cat3: "",
				name: "Tartare Classique",
				description:
					"Bœuf haché au couteau, persil, oignons, câpres, cornichons, sauce Worcestershire, Tabasco",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 16.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Desserts maison",
				cat3: "",
				name: "Muffin du Jour",
				description: "",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 4.0,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Desserts maison",
				cat3: "",
				name: "Digestif Gourmand",
				description:
					"4 petits desserts maison et un mini cookie, Parmi: Cointreau, Menthe Pastille, Armagnac, Peppermint, Cognac aux Amandes, Cognac VS, Poire, Bailey’s, Calvados Closville",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 9.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Desserts glacés",
				cat3: "",
				name: "Coupe de glace (bio)",
				description:
					"Vanille, fraise, chocolat au lait, mangue, melon/menthe, 3C: caramel/chocolat/cacahuète, Suppléments chantilly, amandes, coulis +0,50€",
				price_1_boule: 3.0,
				price_2_boules: 6.0,
				prix_unique: null,
				bio: "(bio)",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
			{
				cat1: "Plats",
				cat2: "Desserts glacés",
				cat3: "",
				name: "Café Glacé",
				description: "Boule vanille et chocolat, café, amandes, chantilly",
				price_1_boule: null,
				price_2_boules: null,
				prix_unique: 7.5,
				bio: "",
				petit: null,
				grand: null,
				contenance: null,
				titrage: null,
				demi: null,
				pinte: null,
				verre: null,
				bouteille: null,
				cl_25: null,
				cl_50: null,
				l_1: null,
			},
		];
	}

		// Users
		const [hpAdmin, hpUser1, hpUser2] = await Promise.all([
			bcrypt.hash("admin", 10),
			bcrypt.hash("user1", 10),
			bcrypt.hash("user2", 10),
		]);
		await Users.bulkCreate([
			{
				firstname: "Admin",
				lastname: "Brasserie",
				email: "admin@bdc.fr",
				password: hpAdmin,
				phone: "0600000001",
				admin: true,
			},
			{
				firstname: "User",
				lastname: "One",
				email: "user1@bdc.fr",
				password: hpUser1,
				phone: "0600000002",
				admin: false,
			},
			{
				firstname: "User",
				lastname: "Two",
				email: "user2@bdc.fr",
				password: hpUser2,
				phone: "0600000003",
				admin: false,
			},
		]);

		// Events (3 lignes)
		await Events.bulkCreate([
			{
				title: "Soirée Beaujolais Nouveau",
				subtitle: "Dégustation",
				date: "2025-11-20",
				image: "events/beaujolais.jpg",
			},
			{
				title: "Concert acoustique",
				subtitle: "Duo jazz",
				date: "2025-10-25",
				image: "events/jazz.jpg",
			},
			{
				title: "Brunch du dimanche",
				subtitle: "Formule gourmande",
				date: "2025-10-19",
				image: "events/brunch.jpg",
			},
		]);

		// Gallery (3 lignes)
		await Gallery.bulkCreate([
			{
				title: "Salle principale",
				subtitle: "Ambiance bois et laiton",
				image: "gallery/salle-principale.jpg",
			},
			{
				title: "Terrasse",
				subtitle: "Ensoleillée",
				image: "gallery/terrasse.jpg",
			},
			{
				title: "Bar",
				subtitle: "Sélection de bières",
				image: "gallery/bar.jpg",
			},
		]);

		// Staff (3 lignes)
		await Staff.bulkCreate([
			{
				title: "Julien",
				subtitle: "Chef de salle",
				image: "staff/julien.jpg",
			},
			{
				title: "Camille",
				subtitle: "Barista",
				image: "staff/camille.jpg",
			},
			{
				title: "Léo",
				subtitle: "Chef cuisinier",
				image: "staff/leo.jpg",
			},
		]);

		// Suppliers (3 lignes)
		await Suppliers.bulkCreate([
			{
				title: "La Ferme des Alpes",
				subtitle: "Produits laitiers AOP",
				description: "Beurre et fromages fermiers locaux",
				image: "suppliers/ferme-alpes.jpg",
			},
			{
				title: "Brasserie Montagnarde",
				subtitle: "Bière artisanale",
				description: "Gamme blonde, IPA, ambrée",
				image: "suppliers/brasserie-montagnarde.jpg",
			},
			{
				title: "Torréfaction Savoyarde",
				subtitle: "Café de spécialité",
				description: "Assemblages pour espresso et filtre",
				image: "suppliers/torrefaction-savoyarde.jpg",
			},
		]);

		console.log("Seed OK: menu + users + events + gallery + staff + suppliers");
	} catch (err) {
		console.error("Erreur seed combiné:", err);
		process.exit(1);
	}
}

export default seed;
seed();
