import {
	Menu,
	Events,
	Gallery,
	Staff,
	Suppliers,
	sequelize,
	CarteDuJour,
} from "../models/index.js";

async function seed() {
	try {
		await sequelize.sync({ force: true });
		await Menu.bulkCreate(
			rawItems().map((it) => ({
				...it,
				slug_cat2: it.cat2 ? it.cat2.replace(/\s+/g, "_").toLowerCase() : null,
			}))
		);

		function rawItems() {
			return [
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Café bio et équitable 80% Arabica 20% Robusta",
					description: "(Pérou) Brûlerie de la Maine, Etriché",
					intitule: "Petit / Grand",
					prix_1: 1.6,
					prix_2: 3.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Déca",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 1.7,
					prix_2: 1.7,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Café Allongé",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 1.7,
					prix_2: 3.2,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Noisette",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 1.7,
					prix_2: 3.2,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Café Crème",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 2.5,
					prix_2: 4.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Chaï Latte",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 3.5,
					prix_2: 5.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Chocolat au Lait",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 3.5,
					prix_2: 5.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Cappuccino",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Café Viennois",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 2.8,
					prix_2: 6.2,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Chocolat Viennois",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 4.0,
					prix_2: 6.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Macchiato",
					description: "Café, Lait, Caramel ou Chocolat Mai",
					intitule: "Petit / Grand",
					prix_1: 4.5,
					prix_2: 6.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Macchiato royal",
					description: "Café, Lait, Caramel ou Chocolat Maison,Chantilly",
					intitule: "Petit / Grand",
					prix_1: 4.5,
					prix_2: 7.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Café Gourmand",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Cafés",
					cat4: null,
					name: "Thé Gourmand",
					description: null,
					intitule: "Petit / Grand",
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Noir Dammann",
					cat4: null,
					name: "Ceylan",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Noir Dammann",
					cat4: null,
					name: "Earl Grey",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Noir Dammann",
					cat4: null,
					name: "4 Fruits rouge",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Noir Dammann",
					cat4: null,
					name: "Vanille",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Vert Dammann",
					cat4: null,
					name: "Miss dammann ",
					description: " Citron, Fruit de la Passion, Gingembre",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Vert Dammann",
					cat4: null,
					name: "Yunnan",
					description: "Yunnan",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Vert Dammann",
					cat4: null,
					name: "Menthe",
					description: "Menthe",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Thé Vert Dammann",
					cat4: null,
					name: "Jasmin",
					description: "Jasmin",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Infusions Dammann",
					cat4: null,
					name: "Tisane Nuit à Versailles",
					description: "Bergamote, Kiwi, Pêche",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Infusions Dammann",
					cat4: null,
					name: "Tisane Carcadet",
					description: "Passion, Framboise",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Infusions Dammann",
					cat4: null,
					name: "Tisane du Berger",
					description:
						"Tilleul, Verveine, Menthe, Citronnelle, Fleur d’Oranger",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Le chaud",
					cat3: "Infusions Dammann",
					cat4: null,
					name: "Rooibos Citrus",
					description: "Citron Vert, Clémentine, Orange Sanguine",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Les sirops",
					description:
						"Melon, Pastèque, Goyave, Litchi, Grenadine, Passion, Grenade, Fraise, Cerise, Cassis, Mûre, Framboise, Pêche, Menthe, Banane, Violette, Kiwi, Rose, Orgeat, Gingembre, Pamplemousse, Citron, Citronnelle, Pulco",
					intitule: null,
					prix_1: 2.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Les diabolos",
					description:
						"Melon, Pastèque, Goyave, Litchi, Grenadine, Passion, Grenade, Fraise, Cerise, Cassis, Mûre, Framboise, Pêche, Menthe, Banane, Violette, Kiwi, Rose, Orgeat, Gingembre, Pamplemousse, Citron, Citronnelle, Pulco",
					intitule: null,
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Boisson énergisante",
					description: null,
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Orangina, Schweppes",
					description: null,
					intitule: null,
					prix_1: 3.6,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Breizh Cola, Breizh Zero, Breizh Agrumes, Oasis Tropical",
					description: null,
					intitule: null,
					prix_1: 3.8,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Thé glacé maison",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Bissap maison",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Café Frappé",
					description: "Café, Sirop Orgeat, Sucre",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Cacolac",
					description: null,
					intitule: null,
					prix_1: 3.6,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Macchiato glacé",
					description: null,
					intitule: null,
					prix_1: 4.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Schorle Les Filles de l’Ouest",
					description:
						"Citron Fringant, Rhubarbe Pimpante, Menthe Fougueuse, Cassis Truculent, Pomelo Corsé",
					intitule: null,
					prix_1: 4.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Ginger Beer",
					description: null,
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Tensai Tea",
					description: "Thé noir Dammann Glacé, Gingembre",
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Soda Leamo",
					description: "Ginger Ale, Orangeade, Concombre Citron",
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Sansu",
					description: "Soda Yuzu, Gingembre (Vitamine C++)",
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Softs",
					cat4: null,
					name: "Kombucha Penrose",
					description:
						"Thé noir Dammann / Rhubarbe / Clémentine ou Thé Vert Dammann Sencha / Framboise / Menthe",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Bières et Vins Sans Alcool",
					cat4: null,
					name: "Jupiler Bière Sans Alcool",
					description: null,
					intitule: null,
					prix_1: 4.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Bières et Vins Sans Alcool",
					cat4: null,
					name: "Meteor IPA Sans Alcool 0,0%",
					description: null,
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Bières et Vins Sans Alcool",
					cat4: null,
					name: "Tête Haute IPA Presque Sans Alcool 0,5%",
					description: null,
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Bières et Vins Sans Alcool",
					cat4: null,
					name: "Vin Blanc Sans Alcool",
					description: "«Cypher» Domaine de Brau (Sauvignon)",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Bières et Vins Sans Alcool",
					cat4: null,
					name: "Vin Blanc Pétillant Sans Alcool ",
					description: "«Cypher» Domaine de Brau (Sauvignon)",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Jus",
					cat4: null,
					name: "100% Pur Jus local",
					description: "Pomme (53), Raisin (49)",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Jus",
					cat4: null,
					name: "Vergers de la Manse (37)",
					description:
						"Tomate, Pomme/Mangue, Pomme/Framboise, Poire, Ananas, Orange, Pamplemousse, Abricot, Fraise",
					intitule: null,
					prix_1: 4.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Jus",
					cat4: null,
					name: "Bahia",
					description:
						"Jus de Goyave Blanche, Litchi, Citron Vert (Vitamine C++)",
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Jus",
					cat4: null,
					name: "Lhumeau",
					description: "Jus de Raisin Pétillant",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Eaux",
					cat4: null,
					name: "Eau Neuve",
					description: "Eau minérale plate",
					intitule: null,
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Eaux",
					cat4: null,
					name: "Eau Neuve",
					description: "Eau minérale plate",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Eaux",
					cat4: null,
					name: "Eau Neuve",
					description: "Eau minérale gazeuse",
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Eaux",
					cat4: null,
					name: "Plancoët Gazeuse",
					description: null,
					intitule: null,
					prix_1: 4.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Eaux",
					cat4: null,
					name: "Plancoët Gazeuse",
					description: null,
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Virgin Mojito, Virgin Mojito Fruit, Virgin Piña Colada",
					description: null,
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Virgin Spritz, Virgin Hugo Spritz",
					description: null,
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Sawat",
					description: "Purée de Fraise, Jus de Cranberry, Menthe, Tonic",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Acapulco",
					description: "Jus d’Orange, Limonade, Sirop Grenadine, Citron",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Kiribata",
					description: "Jus de Cranberry, Jus d’Orange, Citron Vert Pressé",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Citronnella",
					description: "Jus de Mangue, Sirop de Citronnelle, Jus de Citron",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Ginger Berry Fizz",
					description: "Jus de Cranberry, Citron Vert Pressé, Ginger Beer",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Virgin Red Mojito",
					description: "Jus de Fleur d’Hibiscus, Menthe, Citron Vert",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Kootchooloo",
					description:
						"Jus de Pomme, Concombre, Jus de Citron, Sirop de Gingembre, Menthe",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Jamaican Spice",
					description:
						"Purée de Mangue, Jus d’Orange, Ginger Beer, Sirop Piment Maison",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Softs et Sans Alcool",
					cat3: "Les Cocktails Sans Alcool",
					cat4: null,
					name: "Cloudy",
					description:
						"Jus de Goyave, Sirop de Rose, Jus de Citron Vert, Jus de Fleur d’Hibiscus",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Jäger Bomb, Ti Punch",
					description: null,
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Caïpirinha, Caïpiroska",
					description: "Caïpirinha - fruits +0,50€",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Cuba Libre, Planteur, Tequila Sunrise, Daiquiri, Mojito",
					description: "Daiquiri - fruits +0,50€, Mojito - fruits +0,50€",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Cosmopolitain, Cointreaupolitain, Margarita, Cointreau Fizz, Love on the Beach, Martini Dry, Piña Colada, Russe Blanc",
					description: null,
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Bloody Mary, London Mule, Moscow Mule, Long Island, Mai Thaï",
					description: null,
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Grog",
					description: "Pour se rechauffer",
					intitule: null,
					prix_1: 4.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails Classiques",
					cat4: null,
					name: "Irish Coffee Monkey Shoulder, French Coffee",
					description: "Pour se rechauffer",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Red Mojito",
					description:
						"Rhum, Citron Vert, Menthe, Jus de Fleur d’Hibiscus, Angustura, Sucre",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Spritz Violette",
					description: "Crème de Violette, Eau Gazeuse, Crémant",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Spritz Hugo",
					description:
						"Liqueur Fleur de Sureau, Crémant, Eau Gazeuse, Citron Vert, Zeste de Citron Jaune",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Spritz Angevin",
					description: "Bitter Giffard, Crément de Loire, Eau Gazeuse, Orange",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Sour ",
					description: "Tequila Milagro, Amaretto, Pisco",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Jam Sour",
					description: "Whisky Monkey Shoulder, Confiture, Jus de Citron",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Arapi",
					description: "Vodka, Sirop de Grenade, Citron Vert, Crème Coco",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Arawak",
					description: "Rhum, Menthe, Jus de Goyave, Citron Vert, Sucre",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Pol Lover",
					description:
						"Vodka, Liqueur de Melon, Sirop Framboise, Jus d’Ananas, Jus de Cranberry",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Espresso Martini",
					description: "Vodka, Kahlua, Expresso, Sucre",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Gin Smash",
					description: "Gin Hendrick’s, Basilic, Miel, Citron Jaune Pressé",
					intitule: null,
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Honolulu Punch",
					description:
						"Rhum Sailor Jerry, Purée de Passion, Jus d’Ananas, Sirop de Vanille, Citron Vert",
					intitule: null,
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Papete Punch",
					description: "Rhum, Pomme, Goyave, Citron Vert, Litchi",
					intitule: null,
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Cold Kiss",
					description:
						"Gin Hendrick’s, Sirop de Rose, Citron Vert, Jus de Goyave, Jus de Fleur d’Hibiscus",
					intitule: null,
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Cocktails",
					cat3: "Les Cocktails du moment",
					cat4: null,
					name: "Bolly Mule",
					description:
						"Gin Hendrick’s, Crème de Cassis, Ginger Beer, Sirop de Rose Maison, Citron Vert Pressé",
					intitule: null,
					prix_1: 9.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Blondes",
					cat4: null,
					name: "Meteor Blonde, Lager",
					description: "Brasserie Meteor, Hochfelden, 67",
					intitule: "Demi / Pinte",
					prix_1: 3.0,
					prix_2: 5.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Blondes",
					cat4: null,
					name: "Alpaca Citra, Pale Ale",
					description: "Alpaca, Segré, 49",
					intitule: "Demi / Pinte",
					prix_1: 3.9,
					prix_2: 7.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Blondes",
					cat4: null,
					name: "Wendelinus Blonde, Abbaye",
					description: "Brasserie Meteor, Hochfelden, 67",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Blondes",
					cat4: null,
					name: "La Piautre, Triple",
					description: "La Piautre, La Ménitré, 49",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Blanche",
					cat4: null,
					name: "Alpaca Blanche",
					description: "Alpaca, Segré, 49",
					intitule: "Demi / Pinte",
					prix_1: 3.9,
					prix_2: 7.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "IPA",
					cat4: null,
					name: "La Côale Original, IPA",
					description: "La Côale, Bécon-les-Granits, 49",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "IPA",
					cat4: null,
					name: "Bonne Pâte, Double IPA",
					description: "Brasserie La Bestiole, Saint-Barthélemy, 49",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "IPA",
					cat4: null,
					name: "Patoune, NEIPA",
					description: "Brasserie La Bestiole, Saint-Barthélemy, 49",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Ambrée",
					cat4: null,
					name: "Enaxor, Ambrée",
					description: "La Côale, Bécon-les-Granits, 49",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Fruitées",
					cat4: null,
					name: "Meteor Cerise, Rouge, Fruitée",
					description: "Brasserie Meteor, Hochfelden, 67",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Fruitées",
					cat4: null,
					name: "Slash Mango, Blonde, Fruitée",
					description: "Brasserie La Licorne, Saverne, 67",
					intitule: "Demi / Pinte",
					prix_1: 4.2,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Autres",
					cat4: null,
					name: "Panaché",
					description: null,
					intitule: "Demi / Pinte",
					prix_1: 3.2,
					prix_2: 5.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Autres",
					cat4: null,
					name: "Monaco, Bière sirop",
					description: null,
					intitule: "Demi / Pinte",
					prix_1: 3.2,
					prix_2: 5.8,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pression française",
					cat3: "Autres",
					cat4: null,
					name: "Picon Bière",
					description: null,
					intitule: "Demi / Pinte",
					prix_1: 4.0,
					prix_2: 7.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie Bio Artisanale Penrose, Angers",
					cat4: null,
					name: "Gose",
					description: "Acidulée, Note Cassis & Citron vert",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie Bio Artisanale Penrose, Angers",
					cat4: null,
					name: "Wheat Ale",
					description: "Bière de Blé, Légèrement Argumé",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie Bio Artisanale Penrose, Angers",
					cat4: null,
					name: "DDH Pale Ale",
					description: "Blonde Dorée, Note Fruitée et Amer",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie Bio Artisanale Penrose, Angers",
					cat4: null,
					name: "IPA",
					description: "Blonde Houblonnnée, Douce Amer",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie Bio Artisanale Penrose, Angers",
					cat4: null,
					name: "NEIPA",
					description: "Blonde Houblonnnée, Note Fruité et Florale",
					intitule: null,
					prix_1: 6.9,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "Insouciante",
					description: "Pale Ale",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "Vagabonde",
					description: "Witbier, Orange Sanguine",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "L’Intrépide",
					description: "Sour, Passion, Vanille",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "Pas Commode",
					description: "West Coast IPA",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "La Pépère",
					description: "Stout, Tiramisu",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "L’Exubérante",
					description: "Double NEIPA",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Craft beer locales",
					cat3: "Brasserie La Bestiole, Saint-Barthélemy",
					cat4: null,
					name: "Citraddict",
					description: "DDH, IPA, Citra",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Bières bouteille",
					cat3: null,
					cat4: null,
					name: "Desperados",
					description: "Aromatisée Tequila",
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Bières bouteille",
					cat3: null,
					cat4: null,
					name: "Piautre Noir",
					description: "Stout",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Bières bouteille",
					cat3: null,
					cat4: null,
					name: "Chouffe",
					description: "Blonde",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Bières bouteille",
					cat3: null,
					cat4: null,
					name: "Kasteel Rouge",
					description: "Fruits Rouges",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Apéritifs",
					cat3: null,
					cat4: null,
					name: "Pastis",
					description: null,
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Apéritifs",
					cat3: null,
					cat4: null,
					name: "Martini Blanc, Martini Rouge",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Apéritifs",
					cat3: null,
					cat4: null,
					name: "Porto Blanc, Porto Rouge",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Apéritifs",
					cat3: null,
					cat4: null,
					name: "Suze",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Anjour Rouge AOP",
					description: "Domaine des Hautes Ouches (Cab,Franc)",
					intitule: "Verre / Bouteille",
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Anjou Rouge AOP",
					description: "Domaine du Gerfaut (Cab,Franc)",
					intitule: "Verre / Bouteille",
					prix_1: 3.5,
					prix_2: 18.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Anjou Grolleau",
					description: "Domaine Princé (Grolleau)",
					intitule: "Verre / Bouteille",
					prix_1: 3.5,
					prix_2: 18.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Saumur Champigny AOP",
					description: "Domaine de Bourg Neuf (Cab,Franc)",
					intitule: "Verre / Bouteille",
					prix_1: 4.6,
					prix_2: 25.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Saint Nicolas de Bourgueil AOP",
					description: "Vignoble la Jarnoterie (Cab,Franc)",
					intitule: "Verre / Bouteille",
					prix_1: 4.8,
					prix_2: 26.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Saint Nicolas de Bourgueil AOP",
					description: "Vignoble la Jarnoterie (Cab,Franc) – Demi-bouteille",
					intitule: "Verre / Bouteille",
					prix_1: null,
					prix_2: 15.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Chinon AOP « Les Galuches »",
					description: "Domaine Raffault (Cab,Franc)",
					intitule: "Verre / Bouteille",
					prix_1: 4.9,
					prix_2: 27.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Val de Loire",
					cat4: null,
					name: "Cheverny Rouge HVE « EnCLOS du Petit Chien »",
					description: "Domaine Alpha Loire (Pinot Noir, Gamay)",
					intitule: "Verre / Bouteille",
					prix_1: 5.2,
					prix_2: 28.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "Bordeaux Rouge AOC « Réserve »",
					description:
						"Chateau la Grave de Bertin (Merlot, Cab,Franc, Cab,Sauv)",
					intitule: "Verre / Bouteille",
					prix_1: 3.6,
					prix_2: 19.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "Gravé dans la Roche, IGP Coteaux du Pont du Gard",
					description: "Chateau Boucarut (Syrah, vin nature)",
					intitule: "Verre / Bouteille",
					prix_1: 3.9,
					prix_2: 21.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "La Croix d’Arton, IGP Côte de Gascogne",
					description: "Chateau d’Arton (Merlot, Syrah, Cab,Sauv)",
					intitule: "Verre / Bouteille",
					prix_1: 4.0,
					prix_2: 22.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "Côtes du Rhône village Visan « Notre dame des Vignes »",
					description: "Rhonéa (Grenache noir)",
					intitule: "Verre / Bouteille",
					prix_1: 4.4,
					prix_2: 24.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "Corbières AOP",
					description: "Château du Luc (Grenache noir, Carignan, Syrah)",
					intitule: "Verre / Bouteille",
					prix_1: 4.6,
					prix_2: 25.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "Fitou AOC « Les Mille et Une Parcelles »",
					description: "Mont Tauch (Carignan, Grenache noir, Syrah)",
					intitule: "Verre / Bouteille",
					prix_1: 4.8,
					prix_2: 26.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rouges",
					cat3: "Les Autres Régions",
					cat4: null,
					name: "Saint Chinian « Le Bric à Brac »",
					description:
						"Domaine Calmel , Joseph (Grenache noir, Carignan, Syrah)",
					intitule: "Verre / Bouteille",
					prix_1: 5.2,
					prix_2: 28.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Chardonnay IGP",
					description: "Domaine des Hautes Ouches",
					intitule: "Verre / Bouteille",
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Sauvignon IGP",
					description: "Domaine des Hautes Ouches",
					intitule: "Verre / Bouteille",
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Côte de Gascogne IGP « Les Hauts d’Arton »",
					description: "Chateau d’Arton (Colombard, Cab,Sauv)",
					intitule: "Verre / Bouteille",
					prix_1: 4.0,
					prix_2: 22.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Chenin Anjou Blanc",
					description: "Domaine de Gerfaut (Chenin)",
					intitule: "Verre / Bouteille",
					prix_1: 4.0,
					prix_2: 22.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Viognier IGP Pays d’Oc",
					description: "Domaine Paul Mas (Viognier)",
					intitule: "Verre / Bouteille",
					prix_1: 4.5,
					prix_2: 24.5,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Pinot Blanc AOP Alsace",
					description: "Kuentz Bas (Pinot Blanc)",
					intitule: "Verre / Bouteille",
					prix_1: 4.7,
					prix_2: 15.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Côteaux de l’Aubance",
					description: "Domaine Papin (Chenin blanc)",
					intitule: "Verre / Bouteille",
					prix_1: 3.2,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Blancs",
					cat3: null,
					cat4: null,
					name: "Brut Traditionnel Val de Loire",
					description: "Bouvet Ladubay - 1851 (Chardonnay, Chenin)",
					intitule: "Verre / Bouteille",
					prix_1: 4.0,
					prix_2: 22.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rosés",
					cat3: null,
					cat4: null,
					name: "Rosé de Loire AOP",
					description: "Domaine des Hautes Ouches (Grolleau, Gamay)",
					intitule: "Verre / Bouteille",
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Les Vins Rosés",
					cat3: null,
					cat4: null,
					name: "IGP Méditerranée « Brise Marine »",
					description: "Cercle vignerons de provence (Grenache, Cinsault)",
					intitule: "Verre / Bouteille",
					prix_1: 3.2,
					prix_2: 16.0,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Anjou Rouge AOP",
					description: null,
					intitule: "25cl / 50cl / 1L",
					prix_1: 4.2,
					prix_2: 8.0,
					prix_3: 15.0,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Chardonnay IGP",
					description: null,
					intitule: "25cl / 50cl / 1L",
					prix_1: 4.2,
					prix_2: 8.0,
					prix_3: 15.0,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Sauvignon IGP",
					description: null,
					intitule: "25cl / 50cl / 1L",
					prix_1: 4.2,
					prix_2: 8.0,
					prix_3: 15.0,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Côteaux de l’Aubance AOC",
					description: null,
					intitule: "25cl / 50cl / 1L",
					prix_1: 6.0,
					prix_2: 11.5,
					prix_3: 22.0,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Rosé de Loire AOP",
					description: null,
					intitule: "25cl / 50cl / 1L",
					prix_1: 4.0,
					prix_2: 8.0,
					prix_3: 15.0,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "kir / Kir Cardinal",
					description: null,
					intitule: null,
					prix_1: 2.7,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Kir Pétillant / Kir Breton",
					description: null,
					intitule: null,
					prix_1: 4.2,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Pichet de vin",
					cat3: null,
					cat4: null,
					name: "Cidre Brut",
					description: "(33cl)",
					intitule: null,
					prix_1: 3.8,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Rhum Arrangé Maison",
					description: null,
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Botran",
					description: "doux, fruité",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Doorly’s XO",
					description: "riche, doux, fruits secs",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Barcelo Imperial",
					description: "doux, fruité",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Matusalem 15 ans",
					description: "orange, vanille",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Barbancourt 8 ans",
					description: "puissant, vanillé",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Dictador 12 ans",
					description: "fruits exotiques, vanille",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Flor de Caña 14 ans",
					description: "riche, coco, nougat, épices",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Plantation XO",
					description: "boisée, mangue",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Santa Teresa",
					description: "doux, miel, banane",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Rhums",
					cat3: null,
					cat4: null,
					name: "Zacapa 23 ans",
					description: "noix de muscade",
					intitule: null,
					prix_1: 9.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Single Malt",
					cat4: null,
					name: "Aberlour 10 ans",
					description: "fruité, épicé",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Single Malt",
					cat4: null,
					name: "Laphroaig 10 ans",
					description: "tourbé",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Single Malt",
					cat4: null,
					name: "Armorik",
					description: "très fruité et doux",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Single Malt",
					cat4: null,
					name: "La Piautre « Port Saint Maur »",
					description: "tourbé, fumé, épices",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Single Malt",
					cat4: null,
					name: "Highland Park 12 ans",
					description: "légèrement fumé, doux",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Single Malt",
					cat4: null,
					name: "Caol Ila",
					description: "tourbé et gourmand",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Blended",
					cat4: null,
					name: "Irish Powers",
					description: "fort caractère",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Blended",
					cat4: null,
					name: "Monkey Shoulder",
					description: "rond, fruits frais",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Blended",
					cat4: null,
					name: "Telling Stout Cask",
					description: "café, chocolat, épices",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Blended",
					cat4: null,
					name: "Yamazakura",
					description: "doux, aromatique, iodé",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Blended",
					cat4: null,
					name: "Nikka from the Barrel",
					description: "gros caractère, vanille",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Bourbon",
					cat4: null,
					name: "Maker’s Mark",
					description: "doux",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Whiskies",
					cat3: "Bourbon",
					cat4: null,
					name: "Woodford Reserve",
					description: "boisé, rond",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Gins Tonics",
					cat3: null,
					cat4: null,
					name: "Gin Hendrick’s",
					description: "Schweppes Tonic (10cl)",
					intitule: null,
					prix_1: 7.9,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Gins Tonics",
					cat3: null,
					cat4: null,
					name: "Gin Hendrick’s Orbium",
					description: "Fever Tree Tonic (10cl)",
					intitule: null,
					prix_1: 9.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Gins Tonics",
					cat3: null,
					cat4: null,
					name: "Gin La Piautre « Origin »",
					description: "Fever Tree Tonic (10cl) ",
					intitule: null,
					prix_1: 9.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Gins Tonics",
					cat3: null,
					cat4: null,
					name: "Gin Botanist",
					description: "Fever Tree Tonic (10cl)",
					intitule: null,
					prix_1: 10.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Digestifs",
					cat3: null,
					cat4: null,
					name: "Cointreau, Menthe, Pastille Giffard, Peppermint, Bailey's",
					description: null,
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Digestifs",
					cat3: null,
					cat4: null,
					name: "Poire, Cognac aux Amandes Giffard, Calvados",
					description: null,
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Digestifs",
					cat3: null,
					cat4: null,
					name: "Cognac VS Prestignac",
					description: null,
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Digestifs",
					cat3: null,
					cat4: null,
					name: "Cognac ABK6 VSOP",
					description: null,
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Digestifs",
					cat3: null,
					cat4: null,
					name: "Cointreau Noir",
					description: null,
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: null,
					cat4: null,
					name: "Menthe Pastille",
					description: null,
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: null,
					cat4: null,
					name: "Springbok, Tequila",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: null,
					cat4: null,
					name: "Smooth and Easy",
					description: "Rhum, Mangue, Vanille",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: null,
					cat4: null,
					name: "Ruffle",
					description: "Tequila, Passion, Banane",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: null,
					cat4: null,
					name: "Piscolero",
					description: "Pisco, Grenadine, Jus d’Abricot, Pulco",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: null,
					cat4: null,
					name: "Iros",
					description: "Vodka, Cointreau, Sirop de Cerise, Citron",
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: "Rhum arrangé",
					cat4: null,
					name: "Fraise, Basilic et Vanille",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: "Rhum arrangé",
					cat4: null,
					name: "Orange, Cannelle et Vanille",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: "Rhum arrangé",
					cat4: null,
					name: "Mangue, Passion et Vanille",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "boissons",
					cat2: "Shots",
					cat3: "Rhum arrangé",
					cat4: null,
					name: "Framboise, Citronnelle, Gingembre et Menthe",
					description: null,
					intitule: null,
					prix_1: 3.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Houmous",
					description: "Purée de pois chiche et de sésame",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Tzatziki",
					description: "Yaourt, concombre, échalotes, herbes fraîches",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Rillettes de Thon",
					description: "Thon, mayonnaise, persil, oignons cébette",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Écrasé d’Avocat",
					description: "Avocat, coriandre, piment, huile d’olive, citron",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Rillettes Basques",
					description: "Chorizo, cream cheese, piment d’Espelette",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Mozza",
					description:
						"Mozzarella 50g, pignons, pesto, basilic, tomates séchées",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Tartinades Maison à Partager",
					description:
						"4 choix parmi: Houmous, Tzatziki, Rillettes de Thon, Écrasé d’Avocat, Rillettes Basques, Mozza",
					intitule: null,
					prix_1: 23.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Camembert Rôti",
					description: "Camembert 150g, miel, thym",
					intitule: null,
					prix_1: 10.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Fromage",
					description:
						"Camembert, Comté, Morbier, Chèvre, Laïous, Saint-Nectaire",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Charcuterie",
					description:
						"Bœuf fumé, coppa affinée, filet mignon fumé, saucissons, jambon Bodega Reserva 24 mois",
					intitule: null,
					prix_1: 12.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Mixte",
					description: "Assiette de charcuterie + fromage",
					intitule: null,
					prix_1: 21.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Tapas",
					description:
						"Beignets calamar/oignons/crevettes, accras, mozzarella sticks, poulet, Sauce tartare et épicée, Servi avec frites",
					intitule: null,
					prix_1: 22.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Saucissons 150g",
					description: "Cèpes, Piment, Comté, Nature, Poivre…",
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Frites Maison",
					description: "1 sauce incluse Supplément sauce +0,30€",
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Frites Maison XL",
					description: "2 sauces incluses, Supplément sauce +0,30€",
					intitule: null,
					prix_1: 5.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Assiettes et Planches",
					cat3: null,
					cat4: null,
					name: "Bol de salade verte supplémentaire",
					description: null,
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Soupe et Gaspacho Maison",
					cat3: null,
					cat4: null,
					name: "Demandez au serveur pour la soupe du jour",
					description: null,
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: null,
					cat4: null,
					name: "Vosgienne",
					description:
						"Lardons, dés d’emmental, tomates séchées, salade, croûtons",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: null,
					cat4: null,
					name: "César",
					description:
						"Poulet, grana padano, tomates séchées, champignons, sauce César, salade, croûtons",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: null,
					cat4: null,
					name: "Thaï",
					description:
						"Poulet pané, carottes râpées, cébettes, chou, miel, sésame noir, sauce teriyaki, salade",
					intitule: null,
					prix_1: 14.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Végétarien",
					cat4: null,
					name: "Automnale",
					description: "Avocat, pommes, betteraves, noix, céleri, salade",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Végétarien",
					cat4: null,
					name: "Estival",
					description: "Melon, feta, basilic, salade",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Végétarien",
					cat4: null,
					name: "Soleil",
					description: "Aubergines, noix, feta, tomates séchées, salade",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Végétarien",
					cat4: null,
					name: "Falafel",
					description:
						"Falafels maison, houmous, tzatziki, betteraves, maïs, olives, cornichons, sésames, salade, sauce épicée",
					intitule: null,
					prix_1: 11.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Végétarien",
					cat4: null,
					name: "Italienne",
					description:
						"Mozzarella burrata, concombre, basilic, tomates, pignons, roquette, pesto, huile d’olive",
					intitule: null,
					prix_1: 15.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Salades de pâtes froides",
					cat4: null,
					name: "Provençale",
					description:
						"Courgettes, poivrons, aubergines, tomates, oignons, pâtes fusilli",
					intitule: null,
					prix_1: 10.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Salades de pâtes froides",
					cat4: null,
					name: "Saumon",
					description:
						"Saumon, billes de mozzarella di bufala, aneth, concombre, pâtes fusilli",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Salades de pâtes froides",
					cat4: null,
					name: "Thon",
					description:
						"Thon, maïs, olives, tomates cerises, concombre, cornichons, pâtes fusilli",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Salades",
					cat3: "Salades de pâtes froides",
					cat4: null,
					name: "Brésilienne",
					description:
						"Poulet, mangue, concombre, olives, tomates cerises, roquette, maïs, mayonnaise, pâtes fusilli",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Pitchoun",
					description: "Steak 90g, cheddar, salade, ketchup",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Classique",
					description:
						"Steak, cheddar, cornichons, tomates, sauce cocktail, salade",
					intitule: null,
					prix_1: 9.9,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Forestier",
					description: "Steak, comté affiné, champignons, sauce poivre",
					intitule: null,
					prix_1: 12.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Savoyard",
					description: "Steak, coppa, reblochon, salade, sauce poivre",
					intitule: null,
					prix_1: 13.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Lombard",
					description: "Steak, gorgonzola, noix, salade, confit de figues",
					intitule: null,
					prix_1: 13.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Chèvre",
					description: "Steak, chèvre, crème fraîche, thym, salade, miel",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Rosbeef",
					description:
						"Viande de bœuf (langue de chat), champignons, comté affiné, confiture d’oignons maison",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Xalapa",
					description:
						"Viande de bœuf (langue de chat), mozzarella, salade, sauce spéciale maison",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Burrata",
					description: "Steak, mini burrata, tomates séchées, roquette, pesto",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Oriental",
					description:
						"Steak, cheddar, aubergine, poivron, oignons, cumin, cornichons, tomates, salade, sauce samouraï",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Auvergnat",
					description:
						"Steak, Saint-Nectaire, poitrine fumée, oignon rouge, sauce moutarde miel",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Bœuf",
					cat4: null,
					name: "Colombien",
					description: "Steak, feta, écrasé d’avocat, oignons, tomates, salade",
					intitule: null,
					prix_1: 14.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Végétarien",
					cat4: null,
					name: "Phénicien",
					description:
						"Falafel maison, cheddar, roquette, cornichons, tomates, salade, tzatziki maison",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Végétarien",
					cat4: null,
					name: "Veggie",
					description:
						"Galette de pommes de terre maison, aubergine, courgette, poivron, tomate, cheddar, cornichons, salade, sauce cocktail",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Poulet",
					cat4: null,
					name: "Chicken",
					description:
						"Poulet frit, gouda, cumin, cornichon, tomate, salade, sauce barbecue",
					intitule: null,
					prix_1: 12.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Poulet",
					cat4: null,
					name: "Héllène",
					description:
						"Filet de poulet citronné, roquette, cornichons, curcuma, tomates, salade, tzatziki maison",
					intitule: null,
					prix_1: 13.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Poulet",
					cat4: null,
					name: "Suprême",
					description:
						"Poulet frit, écrasé d’avocat, oignon rouge, grana padano",
					intitule: null,
					prix_1: 13.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Poisson",
					cat4: null,
					name: "Marin",
					description:
						"Filet de cabillaud pané, gouda, roquette, cornichons, tomates, salade, sauce tartare maison",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Pour les enfants",
					cat4: null,
					name: "Steak 90g",
					description: "Servi avec salade verte",
					intitule: null,
					prix_1: 8.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Pour les enfants",
					cat4: null,
					name: "Burger Pitchoun",
					description: "Steak 90g, cheddar, ketchup, salade",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Pour les enfants",
					cat4: null,
					name: "Milanaise 90g",
					description: "Servie avec salade verte",
					intitule: null,
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Pour les enfants",
					cat4: null,
					name: "Fish n’Chips 90g",
					description: "Sauce au choix, Servi avec salade verte",
					intitule: null,
					prix_1: 9.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Burgers",
					cat3: "Pour les enfants",
					cat4: null,
					name: "Spaghetti ou Radiatori",
					description:
						"Sauce bolognaise maison ou pesto ou accompagnement du jour, avec parmesan ou emmental",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Chaud",
					cat4: null,
					name: "Poulet",
					description:
						"Poulet, emmental, champignons, crème fraîche, tomates séchées",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Chaud",
					cat4: null,
					name: "Jambon",
					description:
						"Jambon Bodega 24 mois, mozzarella, champignons, sauce tomate maison",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Chaud",
					cat4: null,
					name: "Montagnarde",
					description:
						"Lardons, pommes de terre, crème fraîche, reblochon, oignons",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Chaud",
					cat4: null,
					name: "Mexicaine",
					description:
						"Viande hachée, mozzarella, poivrons, oignons, sauce tomate maison",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Chaud",
					cat4: null,
					name: "Moussaka",
					description:
						"Viande hachée, mozzarella, aubergines, poivrons, oignons, sauce tomate maison",
					intitule: null,
					prix_1: 11.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Froid",
					cat4: null,
					name: "Norvégienne",
					description:
						"Saumon, noix, fromage frais, crème fraîche, curry, roquette, tomates cerises, ciboulette",
					intitule: null,
					prix_1: 11.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Froid",
					cat4: null,
					name: "Ibérique",
					description:
						"Crème de chorizo, olive verte et noire, roquette, ciboulette, tomates cerises, piment d’Espelette",
					intitule: null,
					prix_1: 11.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Froid",
					cat4: null,
					name: "Rio",
					description:
						"Poulet, mangue, crème fraîche, tomate cerise, ciboulette",
					intitule: null,
					prix_1: 11.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Froid",
					cat4: null,
					name: "Capra",
					description:
						"Jambon Bodega 24 mois, chèvre, miel, roquette, tomates cerises",
					intitule: null,
					prix_1: 11.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Froid",
					cat4: null,
					name: "Thon",
					description:
						"Thon, avocats, olives, oignons nouveaux, persil, concombres, tomates cerises, mayo, ciboulette",
					intitule: null,
					prix_1: 12.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Végan Froid",
					cat4: null,
					name: "Avocado",
					description: "Olives, écrasé d’avocats, tomates cerises",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Végan Froid",
					cat4: null,
					name: "Levantine",
					description:
						"Houmous maison, aubergines, olives, roquette, tomates séchées",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Végétarien Chaud",
					cat4: null,
					name: "Chèvre",
					description: "Chèvre, noix, miel, menthe",
					intitule: null,
					prix_1: 9.9,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Végétarien Chaud",
					cat4: null,
					name: "Méditerranée",
					description: "Aubergines, mozzarella, parmesan, tomates séchées",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Tartines",
					cat3: "Végétarien Chaud",
					cat4: null,
					name: "Italia",
					description: "Pesto, mozzarella, champignons, parmesan, tomates",
					intitule: null,
					prix_1: 10.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plat du Jour",
					cat3: null,
					cat4: null,
					name: "Plat du jour",
					description: null,
					intitule: null,
					prix_1: 13.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plat du Jour",
					cat3: null,
					cat4: null,
					name: "Plat + Dessert du Jour",
					description: null,
					intitule: null,
					prix_1: 17.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plat du Jour",
					cat3: null,
					cat4: null,
					name: "Plat + Dessert + Verre de Vin + Café",
					description: null,
					intitule: null,
					prix_1: 19.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Steak Haché 125g",
					description: "Sauce au choix",
					intitule: null,
					prix_1: 9.9,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Tartare Classique",
					description:
						"Bœuf haché au couteau, persil, oignons, câpres, cornichons, sauce Worcestershire, Tabasco",
					intitule: null,
					prix_1: 16.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Tartare Romain",
					description:
						"Bœuf haché au couteau, parmesan, tomates séchées, pignons, basilic, câpres, pesto",
					intitule: null,
					prix_1: 17.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Onglet 140g",
					description: "Sauce au choix",
					intitule: null,
					prix_1: 17.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Bavette 180g",
					description: "Sauce au choix",
					intitule: null,
					prix_1: 17.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Entrecôte Française 200g",
					description: "Sauce au choix",
					intitule: null,
					prix_1: 19.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Faux-Filet 240g",
					description: "Sauce au choix",
					intitule: null,
					prix_1: 20.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Escalope Milanaise 130g",
					description: "Sauce tartare maison",
					intitule: null,
					prix_1: 15.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Poulet Tendresse 130g",
					description: "Poulet frit, Sauce tomate épicée maison",
					intitule: null,
					prix_1: 15.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Fish n’Chips 130g",
					description: "Sauce tartare maison",
					intitule: null,
					prix_1: 14.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Plats",
					cat3: null,
					cat4: null,
					name: "Spaghetti ou Radiatori",
					description:
						"Sauce bolognaise maison ou pesto ou accompagnement du jour, avec parmesan ou emmental",
					intitule: null,
					prix_1: 9.9,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Cookie du Jour",
					description: null,
					intitule: null,
					prix_1: 2.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Muffin du Jour",
					description: null,
					intitule: null,
					prix_1: 4.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Fondant au Chocolat",
					description: "Supplément glace vanille bio +2,50€",
					intitule: null,
					prix_1: 5.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Crumble",
					description: "Supplément glace vanille bio +2,50€",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Mousse au Chocolat",
					description: null,
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Panna Cotta",
					description: "Coulis caramel, chocolat, fruits rouges ou mangue",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Dessert du Jour",
					description: "Seulement le midi, demandez au serveur",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Crème Brûlée",
					description: null,
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Cheesecake",
					description: "Coulis caramel, chocolat, fruits rouges ou mangue",
					intitule: null,
					prix_1: 6.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Tiramisu",
					description: "Au speculoos et café",
					intitule: null,
					prix_1: 7.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Café Gourmand",
					description: "4 petits desserts maison et un mini cookie",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Thé Gourmand",
					description: "4 petits desserts maison et un mini cookie",
					intitule: null,
					prix_1: 8.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Digestif Gourmand",
					description:
						"4 petits desserts maison et un mini cookie, Parmi: Cointreau, Menthe Pastille, Armagnac, Peppermint, Cognac aux Amandes, Cognac VS, Poire, Bailey’s, Calvados Closville",
					intitule: null,
					prix_1: 9.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts maison",
					cat3: null,
					cat4: null,
					name: "Planche 3 Fromages",
					description: "Comté, Camembert et Laïous",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts glacés",
					cat3: null,
					cat4: null,
					name: "Coupe de glace (bio) – 1 boule",
					description:
						"Vanille, fraise, chocolat au lait, mangue, melon/menthe, 3C: caramel/chocolat/cacahuète, Suppléments chantilly, amandes, coulis +0,50€",
					intitule: null,
					prix_1: 3.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts glacés",
					cat3: null,
					cat4: null,
					name: "Coupe de glace (bio) – 2 boules",
					description:
						"Vanille, fraise, chocolat au lait, mangue, melon/menthe, 3C: caramel/chocolat/cacahuète, Suppléments chantilly, amandes, coulis +0,50€",
					intitule: null,
					prix_1: 6.0,
					prix_2: null,
					prix_3: null,
				},
				{
					cat1: "plats",
					cat2: "Desserts glacés",
					cat3: null,
					cat4: null,
					name: "Café Glacé",
					description: "Boule vanille et chocolat, café, amandes, chantilly",
					intitule: null,
					prix_1: 7.5,
					prix_2: null,
					prix_3: null,
				},
			];
		}

		await CarteDuJour.bulkCreate([
			{
				name: "Soupe de potiron et son lard grillé",
				categorie: "Entrées",
				prix: 9,
			},
			{
				name: "Paté maison et ses croutons",
				categorie: "Entrées",
				prix: 11,
			},
			{
				name: "Hamburger savoyard et bacon",
				categorie: "Plats",
				prix: 15,
			},
			{
				name: "Retour de p^che et ses légumes grillés",
				categorie: "Plats",
				prix: 17,
			},
			{
				name: "Crumble pomme chocolat",
				categorie: "Desserts",
				prix: 11,
			},
			{
				name: "Ile flottante",
				categorie: "Desserts",
				prix: 8,
			},
		]);

		// Events (3 lignes)
		await Events.bulkCreate([
			{
				title: "Soirée Beaujolais Nouveau",
				subtitle: "Dégustation",
				date: "2025-11-20",
				image: "events/beaujolais.jpg",
			},
			{
				title: "Concert acoustique",
				subtitle: "Duo jazz",
				date: "2025-10-25",
				image: "events/jazz.jpg",
			},
			{
				title: "Brunch du dimanche",
				subtitle: "Formule gourmande",
				date: "2025-10-19",
				image: "events/brunch.jpg",
			},
		]);

		// Gallery (3 lignes)
		await Gallery.bulkCreate([
			{
				title: "Salle principale",
				subtitle: "Ambiance bois et laiton",
				image: "gallery/salle-principale.jpg",
			},
			{
				title: "Terrasse",
				subtitle: "Ensoleillée",
				image: "gallery/terrasse.jpg",
			},
			{
				title: "Bar",
				subtitle: "Sélection de bières",
				image: "gallery/bar.jpg",
			},
		]);

		// Staff (3 lignes)
		await Staff.bulkCreate([
			{
				title: "Julien",
				subtitle: "Chef de salle",
				image: "staff/julien.jpg",
			},
			{
				title: "Camille",
				subtitle: "Barista",
				image: "staff/camille.jpg",
			},
			{
				title: "Léo",
				subtitle: "Chef cuisinier",
				image: "staff/leo.jpg",
			},
		]);

		// Suppliers (3 lignes)
		await Suppliers.bulkCreate([
			{
				title: "La Ferme des Alpes",
				subtitle: "Produits laitiers AOP",
				description: "Beurre et fromages fermiers locaux",
				image: "suppliers/ferme-alpes.jpg",
			},
			{
				title: "Brasserie Montagnarde",
				subtitle: "Bière artisanale",
				description: "Gamme blonde, IPA, ambrée",
				image: "suppliers/brasserie-montagnarde.jpg",
			},
			{
				title: "Torréfaction Savoyarde",
				subtitle: "Café de spécialité",
				description: "Assemblages pour espresso et filtre",
				image: "suppliers/torrefaction-savoyarde.jpg",
			},
		]);

		console.log("Seed OK: menu + users + events + gallery + staff + suppliers");
	} catch (err) {
		console.error("Erreur seed combiné:", err);
		process.exit(1);
	}
}

export default seed;
// seed();
