import bcrypt from "bcrypt";
import { sequelize, Menu, Events, Gallery, Staff, Suppliers, Users } from "../models/index.js";

async function seed() {
  try {
    await sequelize.authenticate();

    // Menu (jeu de travail)
    await Menu.bulkCreate([
  {
    cat1: "Le chaud",
    cat2: "Cafés",
    cat3: null,
    name: "Café bio et équitable 80% Arabica 20% Robusta",
    description: "(Pérou) Brûlerie de la Maine, Etriché",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: 1.6,
    grand: 3,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Cafés",
    cat3: null,
    name: "Déca",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: 1.7,
    grand: 1.7,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Cafés",
    cat3: null,
    name: "Café Allongé",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: 1.7,
    grand: 3.2,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Thé noir",
    name: "Ceylan",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Thé noir",
    name: "Earl Grey",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Thé noir",
    name: "4 Fruits rouge",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Thé vert",
    name: "Miss dammann",
    description: "Citron, Fruit de la Passion, Gingembre",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Thé vert",
    name: "Yunnan",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Thé vert",
    name: "Menthe",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Infusions",
    name: "Tisane Nuit à Versailles",
    description: "Bergamote, Kiwi, Pêche",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Infusions",
    name: "Tisane Carcadet",
    description: "Passion, Framboise",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Le chaud",
    cat2: "Thés / infusions Dammann",
    cat3: "Infusions",
    name: "Tisane du Berger",
    description: "Tilleul, Verveine, Menthe, Citronnelle, Fleur d’Oranger",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Softs",
    cat3: null,
    name: "Les sirops",
    description: "Melon, Pastèque, Goyave, Litchi, Grenadine, Passion, Grenade, Fraise, Cerise, Cassis, Mûre, Framboise, Pêche, Menthe, Banane, Violette, Kiwi, Rose, Orgeat, Gingembre, Pamplemousse, Citron, Citronnelle, Pulco",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 2,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(25cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Softs",
    cat3: null,
    name: "Les diabolos",
    description: "Melon, Pastèque, Goyave, Litchi, Grenadine, Passion, Grenade, Fraise, Cerise, Cassis, Mûre, Framboise, Pêche, Menthe, Banane, Violette, Kiwi, Rose, Orgeat, Gingembre, Pamplemousse, Citron, Citronnelle, Pulco",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 2.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(25cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Softs",
    cat3: null,
    name: "Boisson énergisante",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(20cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Bières et Vins Sans Alcool",
    cat3: null,
    name: "Jupiler Bière Sans Alcool",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 4.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(25cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Bières et Vins Sans Alcool",
    cat3: null,
    name: "Meteor IPA Sans Alcool 0,0%",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Bières et Vins Sans Alcool",
    cat3: null,
    name: "Tête Haute IPA Presque Sans Alcool 0,5%",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Jus",
    cat3: null,
    name: "100% Pur Jus local",
    description: "Pomme (53), Raisin (49)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: "local",
    petit: null,
    grand: null,
    contenance: "(25cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Jus",
    cat3: null,
    name: "Vergers de la Manse (37)",
    description: "Tomate, Pomme/Mangue, Pomme/Framboise, Poire, Ananas, Orange, Pamplemousse, Abricot, Fraise",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 4.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(25cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Jus",
    cat3: null,
    name: "Bahia",
    description: "Jus de Goyave Blanche, Litchi, Citron Vert (Vitamine C++)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5,
    bio: "France",
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Eaux",
    cat3: null,
    name: "Eau Neuve",
    description: "Eau minérale plate",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 2.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Eaux",
    cat3: null,
    name: "Eau Neuve",
    description: "Eau minérale plate",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(50cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Eaux",
    cat3: null,
    name: "Eau Neuve",
    description: "Eau minérale gazeuse",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Cocktails Sans Alcool",
    cat3: null,
    name: "Virgin Mojito, Virgin Mojito Fruit, Virgin Piña Colada",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Cocktails Sans Alcool",
    cat3: null,
    name: "Virgin Spritz, Virgin Hugo Spritz",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Softs et Sans Alcool",
    cat2: "Les Cocktails Sans Alcool",
    cat3: null,
    name: "Sawat",
    description: "Purée de Fraise, Jus de Cranberry, Menthe, Tonic",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Cocktails",
    cat2: "Les Cocktails Classiques",
    cat3: null,
    name: "Jäger Bomb, Ti Punch",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Cocktails",
    cat2: "Les Cocktails Classiques",
    cat3: null,
    name: "Caïpirinha, Caïpiroska",
    description: "Caïpirinha - fruits +0,50€",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Cocktails",
    cat2: "Les Cocktails Classiques",
    cat3: null,
    name: "Cuba Libre, Planteur, Tequila Sunrise, Daiquiri, Mojito",
    description: "Daiquiri - fruits +0,50€, Mojito - fruits +0,50€",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Cocktails",
    cat2: "Les Cocktails du moment",
    cat3: null,
    name: "Red Mojito",
    description: "Rhum, Citron Vert, Menthe, Jus de Fleur d’Hibiscus, Angustura, Sucre",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Cocktails",
    cat2: "Les Cocktails du moment",
    cat3: null,
    name: "Spritz Violette",
    description: "Crème de Violette, Eau Gazeuse, Crémant",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Cocktails",
    cat2: "Les Cocktails du moment",
    cat3: null,
    name: "Spritz Hugo",
    description: "Liqueur Fleur de Sureau, Crémant, Eau Gazeuse, Citron Vert, Zeste de Citron Jaune",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Blondes",
    name: "Meteor Blonde, Lager",
    description: "Brasserie Meteor, Hochfelden, 67",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "5%",
    demi: 3,
    pinte: 5.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Blondes",
    name: "Alpaca Citra, Pale Ale",
    description: "Alpaca, Segré, 49",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: null,
    titrage: "5,5%",
    demi: 3.9,
    pinte: 7,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Blondes",
    name: "Wendelinus Blonde, Abbaye",
    description: "Brasserie Meteor, Hochfelden, 67",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "6,8%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Blanche",
    name: "Alpaca Blanche",
    description: "Alpaca, Segré, 49",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: null,
    titrage: "4,7%",
    demi: 3.9,
    pinte: 7,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "IPA",
    name: "La Côale Original, IPA",
    description: "La Côale, Bécon-les-Granits, 49",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "6,2%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "IPA",
    name: "Bonne Pâte, Double IPA",
    description: "Brasserie La Bestiole, Saint-Barthélemy, 49",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "8%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "IPA",
    name: "Patoune, NEIPA",
    description: "Brasserie La Bestiole, Saint-Barthélemy, 49",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "6%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Ambrée",
    name: "Enaxor, Ambrée",
    description: "La Côale, Bécon-les-Granits, 49",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "6%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Fruitées",
    name: "Meteor Cerise, Rouge, Fruitée",
    description: "Brasserie Meteor, Hochfelden, 67",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "5,5%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Fruitées",
    name: "Slash Mango, Blonde, Fruitée",
    description: "Brasserie La Licorne, Saverne, 67",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: "8%",
    demi: 4.2,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Autres",
    name: "Panaché",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: 3.2,
    pinte: 5.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Autres",
    name: "Monaco, Bière sirop",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: 3.2,
    pinte: 5.8,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Pression française",
    cat3: "Autres",
    name: "Picon Bière",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: 4,
    pinte: 7.5,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Craft beer locales",
    cat3: "Brasserie Bio Artisanale Penrose, Angers",
    name: "Gose",
    description: "Acidulée, Note Cassis & Citron vert",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: "3,5%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Craft beer locales",
    cat3: "Brasserie Bio Artisanale Penrose, Angers",
    name: "Wheat Ale",
    description: "Bière de Blé, Légèrement Argumé",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: "4,5%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Craft beer locales",
    cat3: "Brasserie Bio Artisanale Penrose, Angers",
    name: "DDH Pale Ale",
    description: "Blonde Dorée, Note Fruitée et Amer",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: "5%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Craft beer locales",
    cat3: "Brasserie La Bestiole, Saint-Barthélemy",
    name: "Insouciante",
    description: "Pale Ale",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(44cl)",
    titrage: "4,0%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Craft beer locales",
    cat3: "Brasserie La Bestiole, Saint-Barthélemy",
    name: "Vagabonde",
    description: "Witbier, Orange Sanguine",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(44cl)",
    titrage: "5%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Craft beer locales",
    cat3: "Brasserie La Bestiole, Saint-Barthélemy",
    name: "L’Intrépide",
    description: "Sour, Passion, Vanille",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(44cl)",
    titrage: "6%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Bières bouteille",
    cat3: null,
    name: "Desperados",
    description: "Aromatisée Tequila",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: "4,5%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Bières bouteille",
    cat3: null,
    name: "Piautre Noir",
    description: "Stout",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: "5%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Bières",
    cat2: "Bières bouteille",
    cat3: null,
    name: "Chouffe",
    description: "Blonde",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(33cl)",
    titrage: "8%",
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Apéritifs",
    cat2: null,
    cat3: null,
    name: "Pastis",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(3cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Apéritifs",
    cat2: null,
    cat3: null,
    name: "Martini Blanc, Martini Rouge",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(6cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Apéritifs",
    cat2: null,
    cat3: null,
    name: "Porto Blanc, Porto Rouge",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(6cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Val de Loire",
    cat3: null,
    name: "Anjour Rouge AOP",
    description: "Domaine des Hautes Ouches (Cab,Franc)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 2.5,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Val de Loire",
    cat3: null,
    name: "Anjou Rouge AOP",
    description: "Domaine du Gerfaut (Cab,Franc)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 3.5,
    bouteille: 18,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Val de Loire",
    cat3: null,
    name: "Anjou Grolleau",
    description: "Domaine Princé (Grolleau)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 3.5,
    bouteille: 18,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Val de Loire",
    cat3: "Demi-bouteille",
    name: "Saint Nicolas de Bourgueil AOP",
    description: "Vignoble la Jarnoterie (Cab,Franc)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: 15,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Les Autres Régions",
    cat3: null,
    name: "Bordeaux Rouge AOC « Réserve »",
    description: "Chateau la Grave de Bertin (Merlot, Cab,Franc, Cab,Sauv)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 3.6,
    bouteille: 19,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Les Autres Régions",
    cat3: null,
    name: "Gravé dans la Roche, IGP Coteaux du Pont du Gard",
    description: "Chateau Boucarut (Syrah, vin nature)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 3.9,
    bouteille: 21.5,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rouges",
    cat2: "Les Autres Régions",
    cat3: null,
    name: "La Croix d’Arton, IGP Côte de Gascogne",
    description: "Chateau d’Arton (Merlot, Syrah, Cab,Sauv)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 4,
    bouteille: 22,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Blancs",
    cat2: null,
    cat3: null,
    name: "Chardonnay IGP",
    description: "Domaine des Hautes Ouches",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 2.5,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Blancs",
    cat2: null,
    cat3: null,
    name: "Sauvignon IGP",
    description: "Domaine des Hautes Ouches",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 2.5,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Blancs",
    cat2: null,
    cat3: null,
    name: "Côte de Gascogne IGP « Les Hauts d’Arton »",
    description: "Chateau d’Arton (Colombard, Cab,Sauv)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: "(bio)",
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 4,
    bouteille: 22,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rosés",
    cat2: null,
    cat3: null,
    name: "Rosé de Loire AOP",
    description: "Domaine des Hautes Ouches (Grolleau, Gamay)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 2.5,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Les Vins Rosés",
    cat2: null,
    cat3: null,
    name: "IGP Méditerranée « Brise Marine »",
    description: "Cercle vignerons de provence (Grenache, Cinsault)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: 3.2,
    bouteille: 16,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Pichet de vin",
    cat2: null,
    cat3: null,
    name: "Anjou Rouge AOP",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: 4.2,
    cl_50: 8,
    l_1: 15
  },
  {
    cat1: "Pichet de vin",
    cat2: null,
    cat3: null,
    name: "Chardonnay IGP",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: 4.2,
    cl_50: 8,
    l_1: 15
  },
  {
    cat1: "Pichet de vin",
    cat2: null,
    cat3: null,
    name: "Sauvignon IGP",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: 4.2,
    cl_50: 8,
    l_1: 15
  },
  {
    cat1: "Rhums",
    cat2: null,
    cat3: null,
    name: "Rhum Arrangé Maison",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Rhums",
    cat2: null,
    cat3: null,
    name: "Botran",
    description: "doux, fruité",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Rhums",
    cat2: null,
    cat3: null,
    name: "Doorly’s XO",
    description: "riche, doux, fruits secs",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Single Malt",
    cat3: null,
    name: "Aberlour 10 ans",
    description: "fruité, épicé",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Single Malt",
    cat3: null,
    name: "Laphroaig 10 ans",
    description: "tourbé",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Single Malt",
    cat3: null,
    name: "Armorik",
    description: "très fruité et doux",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Blended",
    cat3: null,
    name: "Irish Powers",
    description: "fort caractère",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Blended",
    cat3: null,
    name: "Monkey Shoulder",
    description: "rond, fruits frais",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Blended",
    cat3: null,
    name: "Telling Stout Cask",
    description: "café, chocolat, épices",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 8,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Bourbon",
    cat3: null,
    name: "Maker’s Mark",
    description: "doux",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Whiskies",
    cat2: "Bourbon",
    cat3: null,
    name: "Woodford Reserve",
    description: "boisé, rond",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 8,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Gins Tonics",
    cat2: null,
    cat3: null,
    name: "Gin Hendrick’s",
    description: "Schweppes Tonic (10cl)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.9,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Gins Tonics",
    cat2: null,
    cat3: null,
    name: "Gin Hendrick’s Orbium",
    description: "Fever Tree Tonic (10cl)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 9.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Gins Tonics",
    cat2: null,
    cat3: null,
    name: "Gin La Piautre « Origin »",
    description: "Fever Tree Tonic (10cl)",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 9.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Digestifs",
    cat2: null,
    cat3: null,
    name: "Cointreau, Menthe, Pastille Giffard, Peppermint, Bailey's",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Digestifs",
    cat2: null,
    cat3: null,
    name: "Poire, Cognac aux Amandes Giffard, Calvados",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Digestifs",
    cat2: null,
    cat3: null,
    name: "Cognac VS Prestignac",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(4cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Shots",
    cat2: null,
    cat3: null,
    name: "Menthe Pastille",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(2,5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Shots",
    cat2: null,
    cat3: null,
    name: "Springbok, Tequila",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(2,5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Shots",
    cat2: null,
    cat3: null,
    name: "Smooth and Easy",
    description: "Rhum, Mangue, Vanille",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(2,5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Shots",
    cat2: "Rhum arrangé",
    cat3: null,
    name: "Rhum Arrangé",
    description: "Fraise, Basilic et Vanille",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(2,5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Shots",
    cat2: "Rhum arrangé",
    cat3: null,
    name: "Rhum Arrangé",
    description: "Orange, Cannelle et Vanille",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(2,5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Shots",
    cat2: "Rhum arrangé",
    cat3: null,
    name: "Rhum Arrangé",
    description: "Mangue, Passion et Vanille",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 3.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: "(2,5cl)",
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Assiettes et Planches",
    cat2: null,
    cat3: null,
    name: "Houmous",
    description: "Purée de pois chiche et de sésame",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Assiettes et Planches",
    cat2: null,
    cat3: null,
    name: "Tzatziki",
    description: "Yaourt, concombre, échalotes, herbes fraîches",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 6.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Assiettes et Planches",
    cat2: null,
    cat3: null,
    name: "Rillettes de Thon",
    description: "Thon, mayonnaise, persil, oignons cébette",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Soupe/Gaspacho Maison",
    cat2: null,
    cat3: null,
    name: "Demandez au serveur pour la soupe du jour",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades",
    cat2: null,
    cat3: null,
    name: "Vosgienne",
    description: "Lardons, dés d’emmental, tomates séchées, salade, croûtons",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades",
    cat2: null,
    cat3: null,
    name: "César",
    description: "Poulet, grana padano, tomates séchées, champignons, sauce César, salade, croûtons",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades",
    cat2: null,
    cat3: null,
    name: "Thaï",
    description: "Poulet pané, carottes râpées, cébettes, chou, miel, sésame noir, sauce teriyaki, salade",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 14,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades",
    cat2: "Végétarien",
    cat3: null,
    name: "Automnale",
    description: "Avocat, pommes, betteraves, noix, céleri, salade",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades",
    cat2: "Végétarien",
    cat3: null,
    name: "Estival",
    description: "Melon, feta, basilic, salade",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades",
    cat2: "Végétarien",
    cat3: null,
    name: "Soleil",
    description: "Aubergines, noix, feta, tomates séchées, salade",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades de pâtes froides",
    cat2: null,
    cat3: null,
    name: "Provençale",
    description: "Courgettes, poivrons, aubergines, tomates, oignons, pâtes fusilli",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades de pâtes froides",
    cat2: null,
    cat3: null,
    name: "Saumon",
    description: "Saumon, billes de mozzarella di bufala, aneth, concombre, pâtes fusilli",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Salades de pâtes froides",
    cat2: null,
    cat3: null,
    name: "Thon",
    description: "Thon, maïs, olives, tomates cerises, concombre, cornichons, pâtes fusilli",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Bœuf",
    cat3: null,
    name: "Pitchoun",
    description: "Steak 90g, cheddar, salade, ketchup",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 8,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Bœuf",
    cat3: null,
    name: "Classique",
    description: "Steak, cheddar, cornichons, tomates, sauce cocktail, salade",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 9.9,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Bœuf",
    cat3: null,
    name: "Forestier",
    description: "Steak, comté affiné, champignons, sauce poivre",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 12.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Végétarien",
    cat3: null,
    name: "Phénicien",
    description: "Falafel maison, cheddar, roquette, cornichons, tomates, salade, tzatziki maison",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Végétarien",
    cat3: null,
    name: "Veggie",
    description: "Galette de pommes de terre maison, aubergine, courgette, poivron, tomate, cheddar, cornichons, salade, sauce cocktail",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Poulet",
    cat3: null,
    name: "Chicken",
    description: "Poulet frit, gouda, cumin, cornichon, tomate, salade, sauce barbecue",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 12,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Poulet",
    cat3: null,
    name: "Héllène",
    description: "Filet de poulet citronné, roquette, cornichons, curcuma, tomates, salade, tzatziki maison",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 13,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Poulet",
    cat3: null,
    name: "Suprême",
    description: "Poulet frit, écrasé d’avocat, oignon rouge, grana padano",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 13.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Poisson",
    cat3: null,
    name: "Marin",
    description: "Filet de cabillaud pané, gouda, roquette, cornichons, tomates, salade, sauce tartare maison",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Pour les enfants",
    cat3: null,
    name: "Steak 90g",
    description: "Servi avec salade verte",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 8,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Pour les enfants",
    cat3: null,
    name: "Burger Pitchoun",
    description: "Steak 90g, cheddar, ketchup, salade",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Burgers",
    cat2: "Pour les enfants",
    cat3: null,
    name: "Milanaise 90g",
    description: "Servie avec salade verte",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 8.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Chaud",
    cat3: null,
    name: "Poulet",
    description: "Poulet, emmental, champignons, crème fraîche, tomates séchées",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Chaud",
    cat3: null,
    name: "Jambon",
    description: "Jambon Bodega 24 mois, mozzarella, champignons, sauce tomate maison",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Chaud",
    cat3: null,
    name: "Montagnarde",
    description: "Lardons, pommes de terre, crème fraîche, reblochon, oignons",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Froid",
    cat3: null,
    name: "Norvégienne",
    description: "Saumon, noix, fromage frais, crème fraîche, curry, roquette, tomates cerises, ciboulette",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Froid",
    cat3: null,
    name: "Ibérique",
    description: "Crème de chorizo, olive verte et noire, roquette, ciboulette, tomates cerises, piment d’Espelette",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Froid",
    cat3: null,
    name: "Rio",
    description: "Poulet, mangue, crème fraîche, tomate cerise, ciboulette",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 11.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Végan Froid",
    cat3: null,
    name: "Avocado",
    description: "Olives, écrasé d’avocats, tomates cerises",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Végan Froid",
    cat3: null,
    name: "Levantine",
    description: "Houmous maison, aubergines, olives, roquette, tomates séchées",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Végétarien Chaud",
    cat3: null,
    name: "Chèvre",
    description: "Chèvre, noix, miel, menthe",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 9.9,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Végétarien Chaud",
    cat3: null,
    name: "Méditerranée",
    description: "Aubergines, mozzarella, parmesan, tomates séchées",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Tartines",
    cat2: "Végétarien Chaud",
    cat3: null,
    name: "Italia",
    description: "Pesto, mozzarella, champignons, parmesan, tomates",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 10.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Plat du Jour",
    cat2: null,
    cat3: null,
    name: "Plat du jour",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 13,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Plat du Jour",
    cat2: null,
    cat3: null,
    name: "Plat + Dessert du Jour",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 17.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Plat du Jour",
    cat2: null,
    cat3: null,
    name: "Plat + Dessert + Verre de Vin + Café",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 19,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Plats",
    cat2: null,
    cat3: null,
    name: "Steak Haché 125g",
    description: "Sauce au choix",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 9.9,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Plats",
    cat2: null,
    cat3: null,
    name: "Tartare Classique",
    description: "Bœuf haché au couteau, persil, oignons, câpres, cornichons, sauce Worcestershire, Tabasco",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 16.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Plats",
    cat2: null,
    cat3: null,
    name: "Tartare Romain",
    description: "Bœuf haché au couteau, parmesan, tomates séchées, pignons, basilic, câpres, pesto",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 17.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Desserts maison",
    cat2: null,
    cat3: null,
    name: "Cookie du Jour",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 2.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Desserts maison",
    cat2: null,
    cat3: null,
    name: "Muffin du Jour",
    description: null,
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 4,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Desserts maison",
    cat2: null,
    cat3: null,
    name: "Fondant au Chocolat",
    description: "Supplément glace vanille bio +2,50€",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Desserts glacés",
    cat2: null,
    cat3: null,
    name: "Coupe de glace (bio)",
    description: "Vanille, fraise, chocolat au lait, mangue, melon/menthe, 3C: caramel/chocolat/cacahuète, Suppléments chantilly, amandes, coulis +0,50€",
    price_1_boule: 3,
    price_2_boules: 6,
    prix_unique: null,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  },
  {
    cat1: "Desserts glacés",
    cat2: null,
    cat3: null,
    name: "Café Glacé",
    description: "Boule vanille et chocolat, café, amandes, chantilly",
    price_1_boule: null,
    price_2_boules: null,
    prix_unique: 7.5,
    bio: null,
    petit: null,
    grand: null,
    contenance: null,
    titrage: null,
    demi: null,
    pinte: null,
    verre: null,
    bouteille: null,
    cl_25: null,
    cl_50: null,
    l_1: null
  }
]);

    // Users
    const [hpAdmin, hpUser1, hpUser2] = await Promise.all([
      bcrypt.hash("admin", 10),
      bcrypt.hash("user1", 10),
      bcrypt.hash("user2", 10),
    ]);
    await Users.bulkCreate([
      {
        firstname: "Admin",
        lastname: "Brasserie",
        email: "admin@bdc.fr",
        password: hpAdmin,
        phone: "0600000001",
        admin: true,
      },
      {
        firstname: "User",
        lastname: "One",
        email: "user1@bdc.fr",
        password: hpUser1,
        phone: "0600000002",
        admin: false,
      },
      {
        firstname: "User",
        lastname: "Two",
        email: "user2@bdc.fr",
        password: hpUser2,
        phone: "0600000003",
        admin: false,
      },
    ]);

    // Events (3 lignes)
    await Events.bulkCreate([
      {
        title: "Soirée Beaujolais Nouveau",
        subtitle: "Dégustation",
        date: "2025-11-20",
        image: "events/beaujolais.jpg",
      },
      {
        title: "Concert acoustique",
        subtitle: "Duo jazz",
        date: "2025-10-25",
        image: "events/jazz.jpg",
      },
      {
        title: "Brunch du dimanche",
        subtitle: "Formule gourmande",
        date: "2025-10-19",
        image: "events/brunch.jpg",
      },
    ]);

    // Gallery (3 lignes)
    await Gallery.bulkCreate([
      {
        title: "Salle principale",
        subtitle: "Ambiance bois et laiton",
        image: "gallery/salle-principale.jpg",
      },
      {
        title: "Terrasse",
        subtitle: "Ensoleillée",
        image: "gallery/terrasse.jpg",
      },
      {
        title: "Bar",
        subtitle: "Sélection de bières",
        image: "gallery/bar.jpg",
      },
    ]);

    // Staff (3 lignes)
    await Staff.bulkCreate([
      {
        title: "Julien",
        subtitle: "Chef de salle",
        image: "staff/julien.jpg",
      },
      {
        title: "Camille",
        subtitle: "Barista",
        image: "staff/camille.jpg",
      },
      {
        title: "Léo",
        subtitle: "Chef cuisinier",
        image: "staff/leo.jpg",
      },
    ]);

    // Suppliers (3 lignes)
    await Suppliers.bulkCreate([
      {
        title: "La Ferme des Alpes",
        subtitle: "Produits laitiers AOP",
        description: "Beurre et fromages fermiers locaux",
        image: "suppliers/ferme-alpes.jpg",
      },
      {
        title: "Brasserie Montagnarde",
        subtitle: "Bière artisanale",
        description: "Gamme blonde, IPA, ambrée",
        image: "suppliers/brasserie-montagnarde.jpg",
      },
      {
        title: "Torréfaction Savoyarde",
        subtitle: "Café de spécialité",
        description: "Assemblages pour espresso et filtre",
        image: "suppliers/torrefaction-savoyarde.jpg",
      },
    ]);

    console.log("Seed OK: menu + users + events + gallery + staff + suppliers");
  } catch (err) {
    console.error("Erreur seed combiné:", err);
    process.exit(1);
  }
}

export default seed;
seed();
