
###
# Get all menu items
GET http://localhost:3001/api/menu
###

###
# Get  menu by cat1
GET http://localhost:3001/api/menu/cat/boissons
###

###
# Get  menu by cat2
GET http://localhost:3001/api/menu/cat2/plats
###

###
# Get menu item by id
GET http://localhost:3001/api/menu/139
###

###
# Update a menu item
PATCH http://localhost:3001/api/menu/139
content-type: application/json

{
    "prix_3" : 1.1
}
###

###
# Delete a menu item
DELETE http://localhost:3001/api/menu/53

###

# Create a menu item
POST http://localhost:3001/api/menu
content-type: application/json

{
    "cat1" : "boissons",
    "name": "test création item"
}
###





